adding additional checks on @target of <ref>
Digital-Humanities-Quarterly/dhq-journal pull request #60
Opened 2024-01-16 22:47 UTC by brgrey

Following a discussion at the weekly production meeting on January 12, this (small) Schematron update adds a rule which checks for intended values of `@target` in the context of `<ref>`.

Its aim is to ensure that when `@target` begins with a '#' (i.e., it is an internal document link) it points to an existing `@xml:id` somewhere in the document. The purpose of this assertion is to help eliminate encoding spelling errors when `<ref>` is used to point to a `<bibl>`, as well as ensure that internal links to elements like sections, figures, tables, and whatever else we assign `@xml:id` values to actually lead readers to their intended destination.

Following the merge of this request, a realistic next step would be to generate a report of `<ref>` elements which fail this new assertion, to aid in fixing broken links within the article corpus.

2024-01-17 03:28 UTC, sydb requested changes
Overall this looks very good. There are a few picayune little details that could be improved, but make no difference. However, there is one problem that could cause false negatives. For whatever reason, DHQ has ½–1 dozen cases of `@target` that start with one or more whitespace characters. Now it turns out that none of those cases are shorthand pointers (i.e., start with ‘#’). But if such a case snuck in, this rule would fail to fire. (Because the 1st character being tested is a whitespace char, not a sharp char.) The fix is to trim off leading whitespace before testing the attribute value. Luckily, XPath includes a function that does exactly this (and a couple other useful things); it is called `normalize-space()`.

Thus
~~~
tei:ref[starts-with(normalize-space(@target),'#')]
~~~

Other minor points that do not really affect validation:

- The function `substring( normalize-space( @target ), 2 )` will strip the initial ‘#’ character off several milliseconds faster than `replace()`.
- The test for `//*/@xml:id` could be as simple as `//@xml:id`.
- Some folks think that using the `id()` function makes the code more readable. I do not have a strong opinion either way.
- If I were an encoder getting this error msg, though, I think I would prefer it be more specific: `The @target of <name/> does not …`.

You may want to take a look at the WWP’s [checking pointers](https://www.wwp-test.neu.edu/research/publications/documentation/other/checking_pointers_in_ODD.html) document, especially [Fig 4](https://www.wwp-test.neu.edu/research/publications/documentation/other/checking_pointers_in_ODD.html#eg04). That document is written presuming you will have your Schematron in an ODD, which DHQ does not, but the basic idea is the same.

2024-01-18 13:39 UTC, amclark42 commented
I haven't tested the code but it looks good! The only change I'd make is to make sure that `<name/>` is reported as plain text. To do so, all you have to do is make sure the pointy brackets are encoded with `&lt;` and `&gt;`, e.g. `&lt;name/&gt;`.

(I'm not sure what would happen if this message were flagged as it currently stands. I suspect the empty element would translate into an empty string: `The target of  does not reference...`.)

2024-01-18 14:21 UTC, brgrey commented
@amclark42, that `<name/>` element you're referencing actually parses the name of the element in which the rule is acting (i.e., `<ref>`, so that the warning message reads: `The @target of ref does not reference an @xml:id in this document`.

2024-01-18 18:33 UTC, amclark42 commented
@brgrey Gotcha!

2024-01-19 19:58 UTC, merged